version: '3.3'

services:
   frontend:
     image: servicedesk-frontend
     depends_on:
       - backend
     restart: always
     networks:
       - servicedesk_internal
       - servicedesk_external
     ports:
       - "80:80"
     environment:
       - API_URL=http://backend:8080

   backend:
     image: servicedesk-backend
     depends_on:
       - db
     restart: always
     networks:
       - servicedesk_internal
     environment:
       SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/servicedesk?useSSL=false&allowPublicKeyRetrieval=true
       SPRING_DATASOURCE_USERNAME: hello
       SPRING_DATASOURCE_PASSWORD: w0rld
       SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
       SPRING_JPA_HIBERNATE_DDL_AUTO: create
       SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.MySQL57Dialect
       SPRING_JPA_GENERATE_DDL: "true"
       SPRING_JPA_SHOW_SQL: "true"
       
   db:
     image: mysql:8.0.19
     networks:
       - servicedesk_internal
     environment:
       MYSQL_ROOT_PASSWORD: sup3rs3cret
       MYSQL_DATABASE: servicedesk
       MYSQL_USER: hello
       MYSQL_PASSWORD: w0rld
     
networks:
    servicedesk_internal:
        external: false
    servicedesk_external:
        external: true
     