apiVersion: v1
kind: Service
metadata:
  name: servicedesk-db
  labels:
    app: servicedesk
    tier: backend
spec:
  type: NodePort
  ports:
  - port: 3306
  selector:
    app: servicedesk
    tier: db
