apiVersion: v1
kind: Service
metadata:
  name: servicedesk-backend
  labels:
    app: servicedesk
    tier: backend
spec:
  type: LoadBalancer
  ports:
  - port: 8080
  selector:
    app: servicedesk
    tier: backend
